name: 📖 Documentation request
description: Suggest to document a part of the project
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the part of project you would like to be documented.
        A clear and concise description of what you want to happen.
