name: ⛔ Failing tests
description: Request a new feature or enhancement
title: "[TESTS]: "
labels: ["testing"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the desired feature as clear as possible

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Which test(s) are failing?
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the error like logs, links, screenshots, etc.
